### ISSUE TITLE
Adding the time stamp on Cloudsat orbit plot

### ISSUE THREAD

**Issue by albe1982** [dennissergeev/cloudsat_polarlows#2]
Hi, 
thank you very much for this code.
Would it be possible to attach the time stamp on orbit plot (each 5, 30 or 60 minutes)?
I investigated some older Cloudsat codes but they do not deal with this and my understanding of coding and Cloudsat data is far away from the level to implement this by myself:)
![image](https://user-images.githubusercontent.com/59574254/124455113-7c43ac80-dd89-11eb-87ab-4d4b6a5e441d.png)

Kind regards,
Alen

**Comment by dennissergeev** [comment]
Hi Alen,

It's more related to `matplotlib` rather than the CloudSat product itself: if you have a sequence of date-times (e.g. from CloudSat GEOPROF file), you can use them as text which you can add to the plot. I have an old example here: https://dennissergeev.github.io/blog/2015/11/15/dissecting-patricia
The code to add time stamps is this:
```python
_ = [
    ax.plot(
        i,
        j,
        marker=r"${}$".format(it.strftime("%H:%M:%S")),
        mec="r",
        mfc="r",
        ms=60,
        color="r",
        zorder=100,
    )
    for (i, j, it) in zip(x_lab, y_lab, cldst_time[i1:i2:llstep])
]
```
In other words, it's just a loop over times/positions which you add to the plot. I used `ax.plot()` and put the text itself in the `marker=` argument. You can also use the `ax.text()` function instead of `ax.plot()`.

Hope this helps,
Denis

**Comment by albe1982** [comment]
Hi Denis, 
thank you for your fast response. Yes, this was helpful and I managed to add a timestamp.
Thank you for the link for your blog, much appreciated.

Kind regards,
Alen
